# Generated by Django 5.0.1 on 2024-01-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekermodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cpga',
            field=models.CharField(max_length=5),
        ),
    ]
